In [3]:
# Step 1: Import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Step 2: Create sample dataset
# Example: Hours studied vs Exam score
data = {
    "Hours_Studied": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Exam_Score":    [35, 50, 55, 65, 70, 75, 80, 85, 90, 95]
}
df = pd.DataFrame(data)

# Step 3: Define features (X) and target (y)
X = df[["Hours_Studied"]]   # Features must be 2D
y = df["Exam_Score"]        # Target is 1D

# Step 4: Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Step 5: Create and train the model
model = LinearRegression()
model.fit(X_train, y_train)

# Step 6: Check learned parameters
print("Slope (m):", model.coef_[0])
print("Intercept (b):", model.intercept_)

# Step 7: Make predictions
y_pred = model.predict(X_test)
print(y_pred)

# Step 8: Evaluate model
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R² Score:", r2_score(y_test, y_pred))

# Step 9: Predict for new data
new_hours = np.array([[12]])  # Example: 12 hours studied
predicted_score = model.predict(new_hours)
predicted_score = model.predict([[12]])
print("Predicted Exam Score for 12 hours:", predicted_score[0])


Slope (m): 6.379310344827585
Intercept (b): 34.91379310344828
[92.32758621 47.67241379]
Mean Squared Error: 5.41765755053506
R² Score: 0.9864558561236624
Predicted Exam Score for 12 hours: 111.4655172413793


C:\Users\poova\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\poova\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [6]:
# Step 1: Import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Step 2: Create sample dataset
# Example: Predict Exam Score using Hours Studied + Sleep Hours + Previous GPA
data = {
    "Hours_Studied": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Sleep_Hours":   [8, 7, 6, 7, 6, 5, 5, 4, 4, 3],
    "Prev_GPA":      [2.0, 2.2, 2.5, 2.7, 3.0, 3.2, 3.4, 3.6, 3.8, 4.0],
    "Exam_Score":    [40, 50, 55, 65, 70, 75, 80, 85, 90, 95]
}
df = pd.DataFrame(data)

# Step 3: Define features (X) and target (y)
X = df[["Hours_Studied", "Sleep_Hours", "Prev_GPA"]]  # Multiple features (2D)
y = df["Exam_Score"]                                  # Target (1D)

# Step 4: Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Step 5: Create and train the model
model = LinearRegression()
model.fit(X_train, y_train)

# Step 6: Check learned parameters
print("Coefficients (slopes):", model.coef_)
print("Intercept (b):", model.intercept_)

# Step 7: Make predictions
y_pred = model.predict(X_test)

# Step 8: Evaluate model
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R² Score:", r2_score(y_test, y_pred))

# Step 9: Predict for new data
new_data = np.array([[12, 6, 3.5]])  # 12 study hours, 6 sleep hours, GPA 3.5
predicted_score = model.predict(new_data)
print("Predicted Exam Score:", predicted_score[0])


Coefficients (slopes): [-2.41666667  2.41666667 43.61111111]
Intercept (b): -62.388888888888914
Mean Squared Error: 10.290895061728223
R² Score: 0.9742727623456794
Predicted Exam Score: 75.74999999999997


C:\Users\poova\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [7]:
print(X_train.shape)  # (n_train_samples, n_features)
print(y_train.shape)  # (n_train_samples,)
print(X_test.shape)   # (n_test_samples, n_features)
print(y_test.shape)   # (n_test_samples,)


(8, 3)
(8,)
(2, 3)
(2,)


In [8]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly.fit_transform(X)  # Adds squared and interaction terms
X_poly

array([[  1.  ,   8.  ,   2.  ,   1.  ,   8.  ,   2.  ,  64.  ,  16.  ,
          4.  ],
       [  2.  ,   7.  ,   2.2 ,   4.  ,  14.  ,   4.4 ,  49.  ,  15.4 ,
          4.84],
       [  3.  ,   6.  ,   2.5 ,   9.  ,  18.  ,   7.5 ,  36.  ,  15.  ,
          6.25],
       [  4.  ,   7.  ,   2.7 ,  16.  ,  28.  ,  10.8 ,  49.  ,  18.9 ,
          7.29],
       [  5.  ,   6.  ,   3.  ,  25.  ,  30.  ,  15.  ,  36.  ,  18.  ,
          9.  ],
       [  6.  ,   5.  ,   3.2 ,  36.  ,  30.  ,  19.2 ,  25.  ,  16.  ,
         10.24],
       [  7.  ,   5.  ,   3.4 ,  49.  ,  35.  ,  23.8 ,  25.  ,  17.  ,
         11.56],
       [  8.  ,   4.  ,   3.6 ,  64.  ,  32.  ,  28.8 ,  16.  ,  14.4 ,
         12.96],
       [  9.  ,   4.  ,   3.8 ,  81.  ,  36.  ,  34.2 ,  16.  ,  15.2 ,
         14.44],
       [ 10.  ,   3.  ,   4.  , 100.  ,  30.  ,  40.  ,   9.  ,  12.  ,
         16.  ]])

In [10]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[0.        , 1.        , 0.        ],
       [0.11111111, 0.8       , 0.1       ],
       [0.22222222, 0.6       , 0.25      ],
       [0.33333333, 0.8       , 0.35      ],
       [0.44444444, 0.6       , 0.5       ],
       [0.55555556, 0.4       , 0.6       ],
       [0.66666667, 0.4       , 0.7       ],
       [0.77777778, 0.2       , 0.8       ],
       [0.88888889, 0.2       , 0.9       ],
       [1.        , 0.        , 1.        ]])

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[-1.5666989 ,  1.66666667, -1.61167689],
       [-1.21854359,  1.        , -1.30173903],
       [-0.87038828,  0.33333333, -0.83683223],
       [-0.52223297,  1.        , -0.52689437],
       [-0.17407766,  0.33333333, -0.06198757],
       [ 0.17407766, -0.33333333,  0.24795029],
       [ 0.52223297, -0.33333333,  0.55788815],
       [ 0.87038828, -1.        ,  0.86782602],
       [ 1.21854359, -1.        ,  1.17776388],
       [ 1.5666989 , -1.66666667,  1.48770175]])