### Car Prediction 

In [7]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [8]:
df=pd.read_csv("Cars (1).csv")

In [9]:
df

,HP,MPG,VOL,SP,WT
0,49,53.700681,89,104.185353,28.762059
1,55,50.013401,92,105.461264,30.466833
2,55,50.013401,92,105.461264,30.193597
3,70,45.696322,92,113.461264,30.632114
4,53,50.504232,92,104.461264,29.889149
...,...,...,...,...,...
76,322,36.900000,50,169.598513,16.132947
77,238,19.197888,115,150.576579,37.923113
78,263,34.000000,50,151.598513,15.769625
79,295,19.833733,119,167.944460,39.423099


In [15]:
### Independent and Dependent features
X=df.iloc[:,[0,2,3,4]]
y
y=df.iloc[:,1]
y

0     53.700681
1     50.013401
2     50.013401
3     45.696322
4     50.504232
        ...    
76    36.900000
77    19.197888
78    34.000000
79    19.833733
80    12.101263
Name: MPG, Length: 81, dtype: float64

In [19]:
X.head()

,HP,VOL,SP,WT
0,49,89,104.185353,28.762059
1,55,92,105.461264,30.466833
2,55,92,105.461264,30.193597
3,70,92,113.461264,30.632114
4,53,92,104.461264,29.889149


In [17]:
y.head(20)

0     53.700681
1     50.013401
2     50.013401
3     45.696322
4     50.504232
5     45.696322
6     50.013401
7     46.716554
8     46.716554
9     42.299078
10    44.652834
11    39.354094
12    39.354094
13    44.652834
14    45.734893
15    44.652834
16    42.789909
17    39.354094
18    42.789909
19    38.901834
Name: MPG, dtype: float64

In [20]:
### Train Test Split
from sklearn.model_selection import train_test_split

In [22]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0,shuffle=True)
print(X_train,X_test,y_train,y_test)

     HP  VOL          SP         WT
66  165  114  132.484609  37.979956
41   95  106  115.748847  35.027176
3    70   92  113.461264  30.632114
69  245  112  158.300669  37.141733
7    62   50  102.598513  15.847758
..  ...  ...         ...        ...
77  238  115  150.576579  37.923113
67  165  127  133.680223  41.573975
64  150  121  128.128401  40.159482
47   98  103  116.472936  33.910056
44   93  102  114.380966  33.078632

[64 rows x 4 columns]      HP  VOL          SP         WT
22   95  101  120.288996  32.675828
27   92   99  119.105055  32.835069
61  120  116  117.668550  37.860411
13   73   89  111.185353  29.378436
71  162  135  133.415985  44.013139
74  140  129  121.864163  42.618698
30   84  114  113.484609  37.042350
55  130  124  126.404312  40.589068
53  180  113  143.392639  37.620695
26   92  117  120.760520  38.062823
50  115  101  118.288996  33.213954
42  102   92  117.461264  30.527427
48  130   86  127.909442  28.070597
33  102  113  121.392639  37.573290
73  1

In [23]:
### Implement Random Forest classifier
from sklearn.linear_model import LinearRegression
regression=LinearRegression()
regression.fit(X_train,y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [30]:
#train accuracy
y_train_pred=regression.predict(X_train)
y_train_pred

array([26.76907455, 35.5185244 , 42.43729318, 20.72351304, 48.01323784,
       22.31506788, 16.82973854, 34.35901899, 37.93220542, 41.9173949 ,
       23.34241469, 47.72938564, 26.98217133, 48.49688517, 42.27296995,
       32.39428228, 38.86636219, 36.19993108, 37.01518637, 38.65506402,
       47.31297356, 28.47477195, 39.60746166, 41.48368211, 37.29350077,
       36.37438843, 26.94692489, 42.42263459, 36.78613465, 24.75933295,
       41.77516891, 29.16043044, 37.45265683, 36.02026526, 30.22451347,
       33.75674177, 39.50144821, 37.37575   , 41.11083922, 43.04488023,
       13.21628422, 41.71163356, 42.90906033, 25.62384961, 40.73882633,
       33.7361754 , 38.22504649, 21.85655073, 46.60240947, 38.15695955,
       34.21825937, 35.80498195, 36.76439028, 35.59049207, 39.67147306,
       28.12754298, 39.24186017, 37.15349727, 40.55146033, 18.67313755,
       23.86076354, 26.55980748, 35.69255704, 35.6576828 ])

In [32]:
## Prediction
y_pred=regression.predict(X_test)
y_pred

array([37.3617628 , 38.7074597 , 29.06366575, 41.49794875, 22.51118612,
       24.55153852, 34.58741927, 28.54309907, 27.75729402, 34.91819258,
       33.52564075, 37.74914445, 36.78240263, 34.87940581, 19.32579436,
       42.16439053, 33.07251139])

In [33]:
### Check Accuracy
from sklearn.metrics import r2_score
score=r2_score(y_test,y_pred)
print(score)

0.8012359692731323


In [26]:
score

0.8012359692731323

In [35]:
train_score=r2_score(y_train,y_train_pred)
train_score

0.7567680292415555

In [36]:
regression.predict([[165,114,132.484609,37.979956]])

array([26.76907445])

In [38]:
### Create a Pickle file using serialization 
import pickle
pickle_out = open("mlr.pkl","wb")
pickle.dump(regression, pickle_out)
pickle_out.close()

In [39]:
import numpy as np

In [40]:
regression.predict([[165,114,132.484609,37.979956]])

array([26.76907445])

In [41]:
!pip install streamlit

In [42]:
!pip install --upgrade streamlit

   ---------------------------------------- 0.0/9.2 MB ? eta -:--:--
   ------------- -------------------------- 3.1/9.2 MB 18.2 MB/s eta 0:00:01
   ----------------------------------- ---- 8.1/9.2 MB 22.0 MB/s eta 0:00:01
   ---------------------------------------- 9.2/9.2 MB 19.2 MB/s  0:00:00
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   ---------------------------- ----------- 8.1/11.3 MB 41.5 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.3 MB 28.3 MB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 23.7 MB/s  0:00:00

   ---------------------------------------- 0/7 [websockets]
   ---------------------------------------- 0/7 [websockets]
   ---------------------------------------- 0/7 [websockets]
   ---------------------------------------- 0/7 [websockets]
   ----- ---------------------------------- 1/7 [python-multipart]
   ----------- ---------------------------- 2/7 [httptools]
   ----------------- -------

In [43]:
from sklearn.linear_model import Lasso,Ridge

In [44]:
ls = Lasso(alpha=0.01)
ls.fit(X_train,y_train)
y_train_pred_ls = ls.predict(X_train)
y_test_pred_ls = ls.predict(X_test)

In [45]:
r2_score(y_train,y_train_pred_ls)

0.756640423127468

In [46]:
r2_score(y_test,y_test_pred_ls)

0.802967904404088

In [47]:
rd = Ridge(alpha=0.00001)
rd.fit(X_train,y_train)
y_train_pred_rd = rd.predict(X_train)
y_test_pred_rd = rd.predict(X_test)

In [48]:
r2_score(y_train,y_train_pred_rd)

0.7567680292415506

In [49]:
r2_score(y_test,y_test_pred_rd)

0.8012359815803505